title:            Scrawlon
description: "Programming blog and professional portfolio of Baltimore-area
web developer, Scott McGrath"
baseurl: ""
url: "https://scrawlon.github.io"
disqus_shortname: scrawlon
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
    sass_dir: _sass
    style: compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Set CORS for React dev
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Owner/author information
owner:
  name:           Scott McGrath
  avatar:         owner-avatar.jpg
  # Social networking links used in footer. Update and remove as you like.
  social_networks:
    - name:       "Twitter"
      url:        "https://twitter.com/scrawlon"
      icon:       "fa-twitter"
    - name:       "Github"
      url:        "https://github.com/scrawlon"
      icon:       "fa-github"
    - name:       "Linkedin"
      url:        "https://linkedin.com/in/scrawlon"
      icon:       "fa-linkedin-square"
  local_links:
    - name:       "Email"
      url:        "/contact"
      icon:       "fa-envelope"
    - name:       "rss"
      url:        "/feed.xml"
      icon:       "fa-rss"
  social_share_links:
    - name:       "Twitter"
      url:        "https://twitter.com/intent/tweet?text=page.title&url=site.urlpage.url&via=scrawlon&related=scrawlon"
      icon:       "fa-twitter-square"
    - name:       "Facebook"
      url:        "https://facebook.com/sharer.php?u=site.urlpage.url"
      icon:       "fa-facebook-square"
    - name:       "Linkedin"
      url:        "http://www.linkedin.com/shareArticle?mini=true&url=site.urlpage.url&title=page.title&source=scrawlon.com"
      icon:       "fa-linkedin-square"

# Internal pages/posts to include in top navigation
home:
  - title: Scrawlon
    url: /
links:
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Portfolio
    url: /portfolio/
  - title: Contact
    url: /contact/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:     America/New_York
future:       true
markdown: kramdown
permalink: pretty

include:
  - .htaccess
  - js
exclude:
  - lib
  - config.rb
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - package.json
  - package-lock.json
  - node_modules
  - gulpfile.js

collections:
  - slides_home
  - portfolio_projects

empty_array: []
mobile_nav:
  background-image:
    file: blue-blast.jpg
    caption:
      credit:
        name: Eric Sonstroem
        url: https://www.flickr.com/photos/sonstroem/
      license:
        type: Creative Commons
        url: https://creativecommons.org/licenses/by/2.0/
      source: Flickr
      title: Blue blast
      url: https://flic.kr/p/Kgfvw5
